export const dropdownitems = [
    "Action",
    "Comedy",
    "Family",
    "History",
    "Mystery",
    "Sci - Fi",
    "War",
    "Adventure",
    "Crime",
    "Fantasy",
    "Horror",
    "News",
    "Sport",
    "Western",
    "Animation",
    "Documentary",
    "Film-Noir",
    "Music",
    "Reality-TV",
    "Talk-Show",
    "Biography",
    "Drama",
    "Game-Show",
    "Musical",
    "Romance",
    "Thriller",
]